stages:
  preprocess_luna16:
    cmd: lungscan3d preprocess data=luna16
    deps:
      - data/raw/luna16
      - configs/data/luna16.yaml
      - configs/preprocessing/default.yaml
      - lungscan3d/data/preprocessing.py
      - lungscan3d/data/download.py
    outs:
      - data/processed/luna16
