model_repository: triton_model_repository
model_name: lungscan3d
input_path: null
client_url: localhost:8000
http_port: 8000
grpc_port: 8001
metrics_port: 8002
docker_image: nvcr.io/nvidia/tritonserver:24.05-py3
